<a href="https://colab.research.google.com/github/FirstIntegral/Msc-Artificial-Intelligence/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('/content/book2.xlsx')
df

country    salary   age processed
0  Germany  150000.0  24.0       Yes
1   France  200000.0  34.0       Yes
2    Italy  120000.0  29.0        No
3  Germany  100000.0  18.0       Yes
4   France  170000.0   NaN       Yes
5    Italy  110000.0  32.0        No
6  Germany       NaN  19.0        No
7   France   90000.0  43.0       Yes
8    Italy  140000.0  40.0        No
9    Italy  190000.0  45.0       Yes

In [3]:
X = df.iloc[:, 0:3].values
Y = df.iloc[:, -1].values

In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])

X[:, 1:3] = imputer.transform(X[:, 1:3])

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct_object = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X=np.array(ct_object.fit_transform(X))

In [6]:
X

array([[0.0, 1.0, 0.0, 150000.0, 24.0],
       [1.0, 0.0, 0.0, 200000.0, 34.0],
       [0.0, 0.0, 1.0, 120000.0, 29.0],
       [0.0, 1.0, 0.0, 100000.0, 18.0],
       [1.0, 0.0, 0.0, 170000.0, 31.555555555555557],
       [0.0, 0.0, 1.0, 110000.0, 32.0],
       [0.0, 1.0, 0.0, 141111.11111111112, 19.0],
       [1.0, 0.0, 0.0, 90000.0, 43.0],
       [0.0, 0.0, 1.0, 140000.0, 40.0],
       [0.0, 0.0, 1.0, 190000.0, 45.0]], dtype=object)

In [7]:
Y

array(['Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [8]:
Y = Y.reshape(-1,1)
Y

array([['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
le_object = LabelEncoder()

Y = le_object.fit_transform(Y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
Y

array([1, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)
x_train

array([[0.0, 1.0, 0.0, 141111.11111111112, 19.0],
       [1.0, 0.0, 0.0, 170000.0, 31.555555555555557],
       [0.0, 1.0, 0.0, 150000.0, 24.0],
       [0.0, 1.0, 0.0, 100000.0, 18.0],
       [1.0, 0.0, 0.0, 200000.0, 34.0],
       [1.0, 0.0, 0.0, 90000.0, 43.0],
       [0.0, 0.0, 1.0, 140000.0, 40.0],
       [0.0, 0.0, 1.0, 110000.0, 32.0]], dtype=object)